= Cheatsheets

[[QueueOptions]]
== QueueOptions

++++
 Aimed to specify queue consumer settings when calling link
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[autoAck]]`@autoAck`|`Boolean`|+++

+++
|[[keepMostRecent]]`@keepMostRecent`|`Boolean`|+++

+++
|[[maxInternalQueueSize]]`@maxInternalQueueSize`|`Number (int)`|+++

+++
|===

[[RabbitMQConfirmation]]
== RabbitMQConfirmation

++++
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[channelInstance]]`@channelInstance`|`Number (long)`|-
|[[deliveryTag]]`@deliveryTag`|`Number (long)`|-
|[[multiple]]`@multiple`|`Boolean`|-
|[[succeeded]]`@succeeded`|`Boolean`|-
|===

[[RabbitMQOptions]]
== RabbitMQOptions

++++
 RabbitMQ client options, most
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[automaticRecoveryEnabled]]`@automaticRecoveryEnabled`|`Boolean`|+++
Enables or disables automatic connection recovery.
+++
|[[connectionRetries]]`@connectionRetries`|`Number (Integer)`|+++
Set the number of connection retries to attempt when connecting, the <code>null</code> value disables it.
+++
|[[connectionRetryDelay]]`@connectionRetryDelay`|`Number (long)`|+++
Set the delay in milliseconds between connection retries.
+++
|[[connectionTimeout]]`@connectionTimeout`|`Number (int)`|+++
Set the TCP connection timeout, in milliseconds, <code>zero</code> for infinite).
+++
|[[handshakeTimeout]]`@handshakeTimeout`|`Number (int)`|+++
Set the AMQP 0-9-1 protocol handshake timeout, in milliseconds
+++
|[[host]]`@host`|`String`|+++
Set the default host to use for connections.
+++
|[[hostVerificationEnabled]]`@hostVerificationEnabled`|`Boolean`|+++
Set if host verification should take place.
 Should always be set to true in production
+++
|[[includeProperties]]`@includeProperties`|`Boolean`|+++
Set wether to include properties when a broker message is passed on the event bus
+++
|[[networkRecoveryInterval]]`@networkRecoveryInterval`|`Number (long)`|+++
Set how long in milliseconds will automatic recovery wait before attempting to reconnect, default is <code>5000</code>
+++
|[[password]]`@password`|`String`|+++
Set the password to use when connecting to the broker.
+++
|[[port]]`@port`|`Number (int)`|+++
Set the default port to use for connections.
+++
|[[requestedChannelMax]]`@requestedChannelMax`|`Number (int)`|+++
Set the initially requested maximum channel number, <code>zero</code> for unlimited.
+++
|[[requestedHeartbeat]]`@requestedHeartbeat`|`Number (int)`|+++
Set the initially requested heartbeat interval, in seconds, <code>zero</code> for none.
+++
|[[tlsAlgorithm]]`@tlsAlgorithm`|`String`|+++
Set the TLS algorithm
 Default is TLSv1.2
+++
|[[tlsEnabled]]`@tlsEnabled`|`Boolean`|+++
Set if client uses TLS
+++
|[[tlsTrustStore]]`@tlsTrustStore`|`String`|+++
Set the custom trust store to use
 Default is null meaning default trust store
+++
|[[tlsTrustStorePassword]]`@tlsTrustStorePassword`|`String`|+++
Set custom trust store password
 Default is null
+++
|[[uri]]`@uri`|`String`|-
|[[user]]`@user`|`String`|+++
Set the AMQP user name to use when connecting to the broker.
+++
|[[virtualHost]]`@virtualHost`|`String`|+++
Set the virtual host to use when connecting to the broker.
+++
|===

[[RabbitMQPublisherConfirmation]]
== RabbitMQPublisherConfirmation

++++
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[messageId]]`@messageId`|`String`|-
|[[succeeded]]`@succeeded`|`Boolean`|-
|===

[[RabbitMQPublisherOptions]]
== RabbitMQPublisherOptions

++++
 RabbitMQ client options, most
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[maxInternalQueueSize]]`@maxInternalQueueSize`|`Number (int)`|+++

+++
|[[reconnectAttempts]]`@reconnectAttempts`|`Number (Integer)`|+++
Set the number of reconnect attempts to attempt when connecting, the <code>null</code> value disables it.
+++
|[[reconnectInterval]]`@reconnectInterval`|`Number (long)`|+++
Set the delay in milliseconds between connection retries.
+++
|===

