= RabbitMQ Client for Vert.x

A Vert.x client allowing applications to interact with a RabbitMQ broker (AMQP 0.9.1)

**This service is experimental and the APIs are likely to change before settling down.**

== Getting Started

=== Maven

Add the following dependency to your maven project

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-rabbitmq-client</artifactId>
  <version>${maven.version}</version>
</dependency>
----

=== Gradle

Add the following dependency to your gradle project

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'io.vertx:vertx-rabbitmq-client:${maven.version}'
}
----

=== Create a client

You can create a client instance as follows using a full amqp uri:

[source,$lang]
----
{@link examples.RabbitMQExamples#createClientWithUri}
----

Or you can also specify individual parameters manually:

[source,$lang]
----
{@link examples.RabbitMQExamples#createClientWithManualParams}
----

=== Declare exchange with additional config

You can pass additional config parameters to RabbitMQ's exchangeDeclare method

[source, $lang]
----
{@link examples.RabbitMQExamples#exchangeDeclareWithConfig(io.vertx.rabbitmq.RabbitMQClient)}
----

=== Declare queue with additional config

You can pass additional config parameters to RabbitMQs queueDeclare method

[source, $lang]
----
{@link examples.RabbitMQExamples#queueDeclareWithConfig(io.vertx.rabbitmq.RabbitMQClient)}
----

== Operations

The following are some examples of the operations supported by the RabbitMQService API.
Consult the javadoc/documentation for detailed information on all API methods.

=== Publish

Publish a message to a queue

[source,$lang]
----
{@link examples.RabbitMQExamples#basicPublish}
----

=== Publish with confirm

Publish a message to a queue and confirm the broker acknowledged it.

[source,$lang]
----
{@link examples.RabbitMQExamples#basicPublishWithConfirm}
----

=== Consume

Consume messages from a queue

[source,$lang]
----
// Create a stream of messages from a queue
{@link examples.RabbitMQExamples#basicConsumer}
----

[source,$lang]
----
// Create a stream of messages from a queue with a specific options.
// In this case, in order to handel back-pressure all messages will be stored in a internal queue of 1 000 000 elements.
// If queue would exceed the limit incoming messages, old messages will be replaced with new ones.
{@link examples.RabbitMQExamples#basicConsumerOptions(io.vertx.core.Vertx, io.vertx.rabbitmq.RabbitMQClient)}
----

=== Get

Will get a message from a queue

[source,$lang]
----
{@link examples.RabbitMQExamples#getMessage}
----

=== Consume messages without auto-ack

[source,$lang]
----
{@link examples.RabbitMQExamples#consumeWithManualAck}
----

== Running the tests

You will need to have RabbitMQ installed and running with default ports on localhost for this to work.
