= RabbitMQ Client for Vert.x

A Vert.x client allowing applications to interact with a RabbitMQ broker (AMQP 0.9.1)

**This service is experimental and the APIs are likely to change before settling down.**

== Getting Started

=== Maven

Add the following dependency to your maven project

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-rabbitmq-client</artifactId>
  <version>${maven.version}</version>
</dependency>
----

=== Gradle

Add the following dependency to your gradle project

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'io.vertx:vertx-rabbitmq-client:${maven.version}'
}
----

=== Create a client

You can create a client instance as follows using a full amqp uri:

[source,$lang]
----
{@link examples.RabbitMQExamples#createClientWithUri}
----

Or you can also specify individual parameters manually:

[source,$lang]
----
{@link examples.RabbitMQExamples#createClientWithManualParams}
----

=== Declare exchange with additional config

You can pass additional config parameters to RabbitMQ's exchangeDeclare method

[source, $lang]
----
{@link examples.RabbitMQExamples#exchangeDeclareWithConfig(io.vertx.rabbitmq.RabbitMQClient)}
----

=== Declare queue with additional config

You can pass additional config parameters to RabbitMQs queueDeclare method

[source, $lang]
----
{@link examples.RabbitMQExamples#queueDeclareWithConfig(io.vertx.rabbitmq.RabbitMQClient)}
----

== Operations

The following are some examples of the operations supported by the RabbitMQService API.
Consult the javadoc/documentation for detailed information on all API methods.

=== Publish

Publish a message to a queue

[source,$lang]
----
{@link examples.RabbitMQExamples#basicPublish}
----

=== Publish with confirm

Publish a message to a queue and confirm the broker acknowledged it.

[source,$lang]
----
{@link examples.RabbitMQExamples#basicPublishWithConfirm}
----

=== Consume

Consume messages from a queue.

[source,$lang]
----
// Create a stream of messages from a queue
{@link examples.RabbitMQExamples#basicConsumer}
----

At any moment of time you can pause or resume the stream. When stream is paused you won't receive any message.

[source,$lang]
----
{@link examples.RabbitMQExamples#pauseAndResumeConsumer(io.vertx.rabbitmq.RabbitMQConsumer)}
----

There are actually a set of options to specify when creating a consumption stream.

The `QueueOptions` lets you specify:

 * The size of internal queue with `setMaxInternalQueueSize`
 * Should incoming messages be stored when stream is paused with `setBuffer`
 * Should the stream keep more recent messages when queue size is exceed with `setKeepMostRecent`

[source,$lang]
----
{@link examples.RabbitMQExamples#basicConsumerOptions}
----

When you want to stop consuming message from a queue, you can do:

[source,$lang]
----
{@link examples.RabbitMQExamples#cancelConsumer}
----

You can get notified by the end handler when the queue won't process any more messages:

[source,$lang]
----
{@link examples.RabbitMQExamples#endHandlerConsumer}
----

You can set the exception handler to be notified of any error that may occur when a message is processed:

[source,$lang]
----
{@link examples.RabbitMQExamples#exceptionHandler}
----

And finally, you may want to retrive a related to the consumer tag:

[source,$lang]
----
{@link examples.RabbitMQExamples#consumerTag}
----

=== Get

Will get a message from a queue

[source,$lang]
----
{@link examples.RabbitMQExamples#getMessage}
----

=== Consume messages without auto-ack

[source,$lang]
----
{@link examples.RabbitMQExamples#consumeWithManualAck}
----

== Running the tests

You will need to have RabbitMQ installed and running with default ports on localhost for this to work.
